<?php

$en = array(
    // Login page keys
    "e"=>"E",
    "malkhana"=>"Maalkhana",
    "marching"=>"Towards Swachh Bharat",
    "smart"=>"Smart Policing and Marching",
    "project_heading"=>"'Smart Policing and Marching Towards Swacch Bharat'",
    "enter_mobile"=>"Enter Mobile No.",
    "otp_generate"=>"Send Otp",
    // Otp Page Keys
    "validate"=>"Validate",
    "otp_sent"=>"4 digit OTP code has been sent to your registered mobile no.",
    "enter_otp"=>"Please enter OTP to verify your account",
    "not_got_otp"=>"Didn't get the code?",
    "resend_otp"=>"Resend it",

    // Dashbboard Page Keys
    "sidebar_home"=>"HOME",
    "sidebar_register"=>"REGISTER",
    "sidebar_languages"=>"LANGUAGES",
    "sidebar_logout"=>"LOGOUT",
    "dashboard_search"=>"Search Inventory",
    "inward_button"=>"Inward",
    "scrapyard_button"=>"Scrapyard",
    "auction_button"=>"Auction",
    "outward_button"=>"Outward",
    "scrap_auct_button"=>"Scrapyard/Auction",

    "inward_cases" => "Inward Cases",
    "outward_cases" => "Outward Cases",
    "scrapyard_cases" => "Scrapyard Cases",
    "auction_cases" => "Auction Cases",

    // Search Page
    "go_button"=>"Go",
    "no_data"=>"No Data Found",

    // User Form
    "form"=>"form",
    "register_here"=>"Register Here",
    "station_name"=>"Police station name",
    "role_select"=>"Select Role",
    "mobile_number"=>"Mobile Number",
    "address"=>"Address",
    "state"=>"State",
    "select_state"=>"select state",
    "city"=>"City",
    "select_city"=>"select city",
    "submit"=>"Submit",

    "bhasha" => "Language",

    // Inward Form
    "inward_form"=>"Inward Form",
    "category"=>"Category",
    "sub_category"=>"Sub-category",
    "gd_number"=>"G.D. Number",
    "stolen_date"=>"Stolen Date",
    "recovery_date"=>"Date of Recovery",
    "fir_number"=>"F.I.R Number",
    "under_section"=>"Under-Section",
    "recovered_from"=>"Recovered From",
    "recovered_by"=>"Recovered By",
    "accident_date"=>"Accident Date",
    "release_date"=>"Release Date",
    "vehicle_number"=>"Vehicle Number",
    "vehicle_type"=>"Vehicle Type",
    "two_wheeler"=>"Two Wheeler",
    "three_wheeler"=>"Three Wheeler",
    "four_wheeler"=>"Four Wheeler",
    "vehicle_make"=>"Vehicle Make",
    "vehicle_model"=>"Vehicle Model",
    "vehicle_variant"=>"Vehicle Variant",
    "vehicle_color"=>"Vehicle Colour",
    "item_desc"=>"Item Description",
    "attachments"=>"Attachment of vehicle owner (Aadhaar , DL, RC, Insurance )",
    "pictures"=>"Pictures",
    "engine_number"=>"Engine Number",
    "chassis_number"=>"Chassis Number",
    "mv_act"=>"M.V. Act",
    "owner_name"=>"Name of Owner",
    "vehicle_r_number"=>"Vehicle Registration Number",
    "Unclaimed Vehicles"=>"Unclaimed vehicles form",
    "Accidental case"=>"Accidental case form",
    "Jama Talashi"=>"Jama talashi form",
    "MV Act"=>"M.V. Act. form",
    "Stolen Vehicles"=>"Stolen vehicles form",
    "Objects other than vehicles"=>"Objects other than vehicles form",
    "select_lang"=>"Select Language",
    "hindi"=>"Hindi",

    // Outward Form
    "outward_form"=>"Outward Form",
    "na"=> '',

    //Page Titles
    "outward.php" => 'Outward',
    "search.php" => 'Search',
    "dashboard.php" => 'Dashboard',
    "inward.php" => 'Inward',
    "scrapyard.php" => 'Scrapyard',
    "scrapyard_already.php" => 'Scrapyard',
    "auction_already.php" => 'Auction',
    "auction.php" => 'Auction',
    "user.php" => 'Register',
    "language_change.php" => 'Translate',

    "scrapped"=>"Eligible",
    "scrapped_already"=>"Already Present",



);

$hi = array(
    // Login page keys
    "e"=>"ई",
    "malkhana"=>"मालखाना",
    "marching"=>"की ओर अग्रसर",
    "smart"=>"“स्मार्ट पुलिसिंग और स्वच्छ भारत”",
    "enter_mobile"=>"मोबाइल नंबर दर्ज करें",
    "otp_generate"=>"ओटीपी भेजें",
    // Otp Page Keys
    "validate"=>"सत्यापित करें",
    "otp_sent"=>"आपके रजिस्टर्ड मोबाइल नंबर पर 4 अंकों का ओटीपी भेजा गया है",
    "enter_otp"=>"अपना खाता सत्यापित करने के लिए कृपया ओटीपी दर्ज करें",
    "not_got_otp"=>"ओटीपी नहीं मिला?",
    "resend_otp"=>"फिर से भेजें",
    // Dashbboard Page Keys
    "sidebar_home"=>"होम",
    "sidebar_register"=>"रजिस्टर करें",
    "sidebar_languages"=>"भाषा",
    "sidebar_logout"=>"लॉग आउट",
    "dashboard_search"=>"सूची में खोजें",
    "inward_button"=>"इन्वर्ड",
    "scrapyard_button"=>"रद्दीखाना",
    "auction_button"=>"नीलामी",
    "outward_button"=>"आउटवर्ड",
    "scrap_auct_button"=>"रद्दीखाना/नीलामी",

    "inward_cases" => "इन्वर्ड मामले",
    "outward_cases" => "आउटवर्ड मामले",
    "scrapyard_cases" => "रद्दीखाना मामले",
    "auction_cases" => "नीलामी मामले",
    // Search Page
    "go_button"=>"खोजे",
    "no_data"=>"डाटा प्राप्त नहीं हुआ",
    "register_here"=>"रजिस्टर करें",
    "station_name"=>"थाने का नाम दर्ज करें",
    "role_select"=>"भूमिका चुनें",
    "mobile_number"=>"मोबाइल नंबर",
    "address"=>"पता",
    "state"=>"राज्य",
    "select_state"=>"राज्य चुनें",
    "city"=>"शहर",
    "select_city"=>"शहर चुनें",
    "submit"=>"जमा करें",

    "bhasha" => "भाषा",
    // Inward Form
    "form"=>"फॉर्म",
    "inward_form"=>"इन्वर्ड फॉर्म",
    "category"=>"श्रेणी",
    "sub_category"=>"उप-श्रेणी",
    "gd_number"=>"जनरल डायरी नंबर (जीडी नं)",
    "stolen_date"=>"वाहन चोरी होने की तारीख",
    "recovery_date"=>"बरामद की तारीख",
    "fir_number"=>"एफ.आई.आर. संदर्भ संख्या",
    "under_section"=>"आईपीसी धारा के तहत",
    "recovered_from"=>"बरामद हुआ",
    "recovered_by"=>"के द्वारा बरामद",
    "accident_date"=>"दुर्घटना की तारीख",
    "release_date"=>"रिहाई की तारीख",
    "vehicle_number"=>"वाहन संख्या",
    "vehicle_type"=>"वाहन का प्रकार",
    "two_wheeler"=>"2 व्हीलर",
    "three_wheeler"=>"3 व्हीलर",
    "four_wheeler"=>"4 व्हीलर",
    "vehicle_make"=>"वाहन निर्माता",
    "vehicle_model"=>"वाहन का मॉडल",
    "vehicle_variant"=>"वाहन का संस्करण",
    "vehicle_color"=>"वाहन का रंग",
    "item_desc"=>"वस्तु विवरण",
    "attachments"=>"वाहन मालिक के प्रमाण के संलग्न (आधार, ड्राइविंग लाइसेंस, रजिस्ट्रेशन प्रमाणपत्र, बीमा)",
    "pictures"=>"तस्वीरें",
    "engine_number"=>"इंजन संख्या",
    "chassis_number"=>"चेसिस संख्या",
    "mv_act"=>"एम.वी. ऐक्ट",
    "owner_name"=>"मालिक का नाम",
    "vehicle_r_number"=>"वाहन पंजीकरण संख्या",
    "Unclaimed Vehicles"=>"लावारिस वाहन फॉर्म",
    "Jama Talashi"=>"जामा तलाशी फॉर्म",
    "Accidental case"=>"दुर्घटना मामला फॉर्म",
    "MV Act"=>"एम.वी. कार्यवाही फॉर्म",
    "Stolen Vehicles"=>"चोरी हुए वाहनों का फार्म",
    "Objects other than vehicles"=>"अन्य (वाहन के अलावा कुछ और वस्तु) का फार्म",
    "select_lang"=>"भाषा चुने",
    "hindi"=>"हिंदी",

    "outward_form"=>"आउटवर्ड फॉर्म",
    "na"=> '',

    //Page titles
    "outward.php" => 'आउटवर्ड',
    "search.php" => 'सर्च',
    "dashboard.php" => 'होम ',
    "inward.php" => 'इन्वर्ड',
    "scrapyard_already.php" => 'रद्दीखाना',
    "auction_already.php" => 'नीलामी',
    "scrapyard.php" => 'रद्दीखाना',
    "auction.php" => 'नीलामी',
    "user.php" => 'रजिस्टर',
    "language_change.php" => 'भाषा',
    "scrapped"=>"योग्य",
    "scrapped_already"=>"पहले से मौजूद",

);

?>